<a href="https://colab.research.google.com/github/sunnysakib/Data_Visualization/blob/main/lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
list1 = [1,2,3]

In [23]:
list2 = [3,4,5]

In [24]:
list3 = list1 + list2
list3

[1, 2, 3, 3, 4, 5]

In [25]:
import numpy as np
arr1 = np.array(list1)
arr2 = np.array(list2)
arr3 = arr1 + arr2
arr3

array([4, 6, 8])

In [26]:
list3 = [0,0,0]
for i in range(len(list1)):
  list3[i] = list1[i] + list2[i]
list3

[4, 6, 8]

In [27]:
np.mean(list3)

6.0

In [28]:
A = np.array([[1, 2, 0], [4,2,5], [1,0,2]])
A

array([[1, 2, 0],
       [4, 2, 5],
       [1, 0, 2]])

In [102]:
def submatrix(A, row, col):
    submat = []
    for i in range(len(A)):
        if i == row:
            continue
        subrow = []
        for j in range(len(A[0])):
            if j != col:
              subrow.append(A[i][j])
        submat.append(subrow)
    return submat

In [99]:
submatrix(A, 0, 0)

[[2, 5], [0, 2]]

In [124]:
def determinant(A):
    if len(A) == 1:
        return A[0][0]
    det = 0
    for j in range(len(A)):
        if j % 2 == 0:
            sign = 1
        else:
            sign = -1
        det += sign * A[0][j] * determinant(submatrix(A, 0, j))

    return det

In [132]:
 det = determinant(A)
 det

-2

In [116]:
def cofactor_matrix(A):
    cofactors = np.zeros(9).reshape(3,3)
    for i in range(len(A)):
        for j in range(len(A)):
            if (i + j) % 2 == 0:
              sign = 1
            else:
              sign = -1
            submat = submatrix(A, i, j)
            cofactors[i][j] = sign * determinant(submat)

    return cofactors

In [118]:
cofactor = cofactor_matrix(A)
cofactor

array([[ 4., -3., -2.],
       [-4.,  2.,  2.],
       [10., -5., -6.]])

In [119]:
def transpose(cofactor):
  AT = np.zeros(9).reshape(3,3)
  for i in range(len(cofactor)):
    for j in range(len(cofactor[0])):
      AT[i][j] = cofactor[j][i]
  return AT

In [121]:
transpose_mat = transpose(cofactor)
transpose_mat

array([[ 4., -4., 10.],
       [-3.,  2., -5.],
       [-2.,  2., -6.]])

In [130]:
def inverse(mat, det):
  inv = np.zeros(9).reshape(3,3)
  for i in range(len(mat)):
    for j in range(len(mat)):
      inv[i][j] = mat[i][j] / det
  return inv

In [131]:
inverse(transpose_mat, det)

array([[-2. ,  2. , -5. ],
       [ 1.5, -1. ,  2.5],
       [ 1. , -1. ,  3. ]])